eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8799

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /a/**
      serviceId: service-ribbon
    api-b:
      path: /b/**
      serviceId: service-feign