package com.wei.tempm.entity;

public class Person {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.id
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.cname
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.remark
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.id
	 * @return  the value of person.id
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.id
	 * @param id  the value for person.id
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.cname
	 * @return  the value of person.cname
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.cname
	 * @param cname  the value for person.cname
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	public void setCname(String cname) {
		this.cname = cname == null ? null : cname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.remark
	 * @return  the value of person.remark
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.remark
	 * @param remark  the value for person.remark
	 * @mbg.generated  Mon Jan 28 20:25:58 CST 2019
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}