package com.wei.tempm.service.impl;

import com.wei.tempm.entity.Person;
import com.wei.tempm.mapper.PersonMapper;
import com.wei.tempm.mapper.RootMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class PersonServiceImpl extends RootServiceImpl<Person> implements com.wei.tempm.service.PersonService {
    @Autowired
    private PersonMapper dao;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Jan 28 20:25:58 CST 2019
     */
    @Override
    protected RootMapper<Person> getDao() {
        return dao;
    }
    
}